rvm:
  - 2.1.5
script: bundle exec rspec spec
addons:
  postgresql: 9.3
before_script:
  - psql -c "CREATE DATABASE yadm_test;" -U postgres
  - psql -c "CREATE USER yadm WITH PASSWORD 'yadm';" -U postgres
  - mysql -e "CREATE DATABASE yadm_test;" -u root
  - mysql -e "CREATE USER yadm IDENTIFIED BY 'yadm';" -u root
